### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by dians1s** [oqo0/discord-badge#4]
2024-11-08 22:17:32 ERROR    discord.app_commands.tree Ignoring exception in command 'getbadge'
Traceback (most recent call last):
  File "C:\Users\danisPC\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\danisPC\Desktop\discord-badge-main\main.py", line 88, in getbadge
    await interaction.client.clear()
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\danisPC\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\danisPC\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danisPC\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\commands.py", line 872, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'getbadge' raised an exception: TypeError: object NoneType can't be used in 'await' expression

**Comment by no-0-name** [comment]
Try to upgrade to Python 3.8 with these versions.: ```pip install requests==2.32.3 discord.py==2.3.2```
Everything works for me
